
# spring.datasource.url=jdbc:postgresql://localhost:5432/DMS-1
# spring.datasource.username=postgres
# spring.datasource.password=Admin@123456

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

server.port=${PORT:8080}

spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.messages.use-code-as-default-message=true
spring.jackson.deserialization.fail-on-unknown-properties=false

# server.port=8080